set(game_source
    src/main.cpp
    src/game.cpp
    src/menu_scene.cpp
    src/graphics.cpp
    src/settings_scene.cpp
    src/choose_game_scene.cpp
    src/pong_scene.cpp
    src/arkanoid_scene.cpp
    src/collision.cpp
    src/simple_button.cpp 
    src/label.cpp
    src/scene.cpp
    src/main_scene.cpp
    src/message_system.cpp)
